// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import "@fontsource/geist-sans";
import "@fontsource/geist-mono";
import "./globals.css";

export const metadata: Metadata = {
  title: "LucroReal - Gestão Financeira Inteligente",
  description: "Descubra se seu negócio te dá dinheiro ou só te mantém ocupado",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className="font-sans antialiased">
        {children}
      </body>
    </html>
  );
}
